In [ ]:
#Name:P.Sai Prerana
#Regno:24-14-03
#Programme:Modelling and Simulation
#Assignment:2(DSTT)

In [16]:
import numpy as np
#1 question
# a)
var1 = np.arange(0, 31)
print("var1:", var1)
print("Shape of var1:", var1.shape)

var1: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
Shape of var1: (31,)


In [17]:
#b)
var2 = var1[:30].reshape(5, 6)
print("var2:\n", var2)
print("Shape of var2:", var2.shape)

var2:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Shape of var2: (5, 6)


In [18]:
#c)
var3 = var1[:30].reshape(3, 2, 5)
print("\nvar3 (reshaped 3D array):\n", var3)
print("Shape of var3:", var3.shape)


var3 (reshaped 3D array):
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]
Shape of var3: (3, 2, 5)


In [19]:
#d)
var2[1, 0] = -1
print("var2:", var2)

var2: [[ 0  1  2  3  4  5]
 [-1  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [20]:
#e) i)
sum_over_second_dim = np.sum(var3, axis=1)
print("Sum over second dimension:\n", sum_over_second_dim)

Sum over second dimension:
 [[ 5  0  9 11 13]
 [25 27 29 31 33]
 [45 47 49 51 53]]


In [21]:
#e) ii)
sum_var3_axis_3 = np.sum(var3, axis=2)
print("Sum of var3 over third dimension (axis=2):\n", sum_var3_axis_3)

Sum of var3 over third dimension (axis=2):
 [[ 10  28]
 [ 60  85]
 [110 135]]


In [22]:
#e) iii)
sum_var3_axis_1_3 = np.sum(var3, axis=(0, 2))
print("Sum of var3 over first and third dimensions (axis=(0,2)):\n", sum_var3_axis_1_3)

Sum of var3 over first and third dimensions (axis=(0,2)):
 [180 248]


In [23]:
#f) i)
second_row_var2 = var2[1, :]
print("\nSecond row of var2:\n", second_row_var2)


Second row of var2:
 [-1  7  8  9 10 11]


In [24]:
#f) ii)
last_column_var2 = var2[:, -1]
print("\nLast column of var2:\n", last_column_var2)


Last column of var2:
 [ 5 11 17 23 29]


In [25]:
#f) iii)
top_right_2x2 = var2[:2, -2:]
print("\nTop-right 2x2 submatrix of var2:\n", top_right_2x2)


Top-right 2x2 submatrix of var2:
 [[ 4  5]
 [10 11]]


In [26]:
#2nd question
#a)
import numpy as np

vector = np.arange(1, 11)
print("Vector 1 to 10:", vector)


Vector 1 to 10: [ 1  2  3  4  5  6  7  8  9 10]


In [27]:
#b)
i_vals = np.arange(1, 11).reshape(10, 1)
j_vals = np.arange(1, 11)
matrix_A = i_vals + j_vals
print("\nMatrix A (10x10 where A_ij = i + j):\n", matrix_A)


Matrix A (10x10 where A_ij = i + j):
 [[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


In [28]:
#c)
data = np.exp(np.arange(1, 251).reshape(50, 5) / 50)
print("\nFake data set (50x5):\n", data)


Fake data set (50x5):
 [[  1.02020134   1.04081077   1.06183655   1.08328707   1.10517092]
 [  1.12749685   1.1502738    1.17351087   1.19721736   1.22140276]
 [  1.24607673   1.27124915   1.29693009   1.32312981   1.34985881]
 [  1.37712776   1.40494759   1.43332941   1.46228459   1.4918247 ]
 [  1.52196156   1.55270722   1.58407398   1.6160744    1.64872127]
 [  1.68202765   1.71600686   1.7506725    1.78603843   1.8221188 ]
 [  1.85892804   1.89648088   1.93479233   1.97387773   2.01375271]
 [  2.05443321   2.09593551   2.13827622   2.18147227   2.22554093]
 [  2.27049984   2.31636698   2.36316069   2.41089971   2.45960311]
 [  2.50929039   2.55998142   2.61169647   2.66445624   2.71828183]
 [  2.77319476   2.82921701   2.88637099   2.94467955   3.00416602]
 [  3.0648542    3.12676837   3.18993328   3.2543742    3.32011692]
 [  3.38718773   3.45561346   3.52542149   3.59663973   3.66929667]
 [  3.74342138   3.81904351   3.8961933    3.97490163   4.05519997]
 [  4.13712044   4.22069

In [29]:
#d)
mean = np.mean(data, axis=0)
std_dev = np.std(data, axis=0)
print("\nMean of each column:\n", mean)
print("\nStandard deviation of each column:\n", std_dev)


Mean of each column:
 [28.59937047 29.17711608 29.76653292 30.36785678 30.98132818]

Standard deviation of each column:
 [35.39637207 36.11142622 36.84092542 37.58516148 38.34443211]


In [30]:
#e)
normalized = (data - mean) / std_dev
print("\nStandardized data (normalized):\n", normalized)


Standardized data (normalized):
 [[-0.77915242 -0.77915242 -0.77915242 -0.77915242 -0.77915242]
 [-0.77612117 -0.77612117 -0.77612117 -0.77612117 -0.77612117]
 [-0.77277111 -0.77277111 -0.77277111 -0.77277111 -0.77277111]
 [-0.76906872 -0.76906872 -0.76906872 -0.76906872 -0.76906872]
 [-0.76497695 -0.76497695 -0.76497695 -0.76497695 -0.76497695]
 [-0.76045485 -0.76045485 -0.76045485 -0.76045485 -0.76045485]
 [-0.75545715 -0.75545715 -0.75545715 -0.75545715 -0.75545715]
 [-0.74993384 -0.74993384 -0.74993384 -0.74993384 -0.74993384]
 [-0.74382964 -0.74382964 -0.74382964 -0.74382964 -0.74382964]
 [-0.73708345 -0.73708345 -0.73708345 -0.73708345 -0.73708345]
 [-0.72962776 -0.72962776 -0.72962776 -0.72962776 -0.72962776]
 [-0.72138795 -0.72138795 -0.72138795 -0.72138795 -0.72138795]
 [-0.71228155 -0.71228155 -0.71228155 -0.71228155 -0.71228155]
 [-0.70221742 -0.70221742 -0.70221742 -0.70221742 -0.70221742]
 [-0.69109484 -0.69109484 -0.69109484 -0.69109484 -0.69109484]
 [-0.67880248 -0.6788

In [31]:
#e)
normalized_mean = np.mean(normalized, axis=0)
normalized_std_dev = np.std(normalized, axis=0)
print("\nMean of normalized data:\n", normalized_mean)
print("\nStandard deviation of normalized data:\n", normalized_std_dev)


Mean of normalized data:
 [ 8.88178420e-18 -1.77635684e-17 -2.13162821e-16 -6.21724894e-17
 -3.55271368e-17]

Standard deviation of normalized data:
 [1. 1. 1. 1. 1.]


In [34]:
#3rd question
#a)
import numpy as np
import numpy.linalg as la
def vandermonde(N):
 vec = np.arange(N) + 1
 vander = vec[:, np.newaxis] ** vec[np.newaxis, :]
 return vander
N = 12
vander = vandermonde(N)
print("Vandermonde matrix:")
print(vander)

Vandermonde matrix:
[[          1           1           1           1           1           1
            1           1           1           1           1           1]
 [          2           4           8          16          32          64
          128         256         512        1024        2048        4096]
 [          3           9          27          81         243         729
         2187        6561       19683       59049      177147      531441]
 [          4          16          64         256        1024        4096
        16384       65536      262144     1048576     4194304    16777216]
 [          5          25         125         625        3125       15625
        78125      390625     1953125     9765625    48828125   244140625]
 [          6          36         216        1296        7776       46656
       279936     1679616    10077696    60466176   362797056 -2118184960]
 [          7          49         343        2401       16807      117649
       82354

In [35]:
#b)
x = np.ones(N)
b = vander @ x
print("Vector b:")
print(b)

Vector b:
[ 1.20000000e+01  8.19000000e+03  7.97160000e+05  2.23696200e+07
  3.05175780e+08 -1.68282849e+09  3.26326651e+09  1.22713351e+09
 -9.43513640e+07  3.00954874e+09 -8.82491592e+08  2.84907632e+09]


In [37]:
#c)
x_naive = la.inv(vander) @ b
print("Naive solution:\n", x_naive)

Naive solution:
 [1.00000179 1.00016129 0.99997008 1.00000072 1.00000036 0.99999995
 1.         1.         1.         1.         1.         1.        ]


In [38]:
#d)
x_solve = la.solve(vander, b)
print("Solution using np.linalg.solve:", x_solve)

Solution using np.linalg.solve: [1.00000425 0.9999914  1.00000681 0.9999973  1.00000058 0.99999993
 1.         1.         1.         1.         1.         1.        ]
